function  pbmatrix_hp_trim()

%list = [{'17D'};{'17R'};{'ID'}; {'IR'};{'ND'};{'NR'};{'TD'};{'TR'}];
%list = [{'N1R3'};{'N3R3'};{'O2R3'};{'O3R3'};{'T2R3'};{'W4R3'}] ;
list = [{'I2R2'};{'I3R2'};{'N2R2'}; {'N3R2'};{'T2D2'};{'T2R2'};{'W1R2'};{'W4R2'}];
%C:\Users\BAI Lab
folder = 'C:\Users\bailab\Dropbox';%
%folder = 'E:\d\Dropbox';
%mkdir([folder '\Pacbio_analysis\re_start\matrix']);
%mkdir([folder '\Pacbio_analysis\202006_comb\matrix']);

for h = 1:8
    name = list{h,1};
    datam = load([folder, '\Pacbio_analysis\20190830\aligned\aligned_',name,'.mat']);
    %datar = load([folder, '\Pacbio_analysis\re_start\mot_check\mot_check_re_',name,'.mat']);
    seqs_m_all = datam.alignment;
    %seqs_r_all = datar.data;
    for k = 1:169
        seqs_c = seqs_m_all(1,k).reads;
        %seqs_c = seqs_c{1,1};
%         seqs_r = seqs_r_all(k,1);
%         seqs_r = seqs_r{1,1};
        
%         seqs_c = [seqs_m; seqs_r];
        
        position = xlsread([folder, '\Pacbio_analysis\ref\GC_positions.xlsx'], k);
        [~, num_position] = size(position);
        value_sum = zeros(3,num_position);
        value_sum(1,:)=position;
        value_sum(3,:)=position-1208;
        
        %seq_array = data.data(k,1);%Get the cell array(seq_all) in the cell array file(seq_all_cell)which was generated by textscan
        %seq_array = seq_array{1,1};
        %seq_array = {};%build an empty cell for DNA sequences
%          [lenm, widm] = size(seqs_m);
%          [lenr, widr] = size(seqs_r);
        [lenc, ~] = size(seqs_c); 
%         C_T_sum_m = zeros(lenm, widm); %C_T_map is an array that contains the sequencing results at each C of GC position
%         C_T_sum_r = zeros(lenr, widr);
%         C_T_sum_c = zeros(lenc, widc);
        %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
        
%          [C_T_sum_m,value_sum_m]= countreads(position,seqs_m,value_sum);
%          [C_T_sum_r,value_sum_r]= countreads(position,seqs_r,value_sum);
        [C_T_sum_c,~]= countreads(position,seqs_c,value_sum);
        C_T_sum_trim = [];
        for i = 1:lenc
            if sum(C_T_sum_c(i,:)==1)< 4
            %if sum(C_T_sum_c(i,:)==1)< 0
            else
            C_T_sum_trim = [C_T_sum_trim;C_T_sum_c(i,:)];
            end
        end
        [~,widt] = size(C_T_sum_trim);
        value_sum_trim = sum(C_T_sum_trim)/widt;
        %xlswrite(['E:\d\Dropbox\Pacbio_analysis\reb1_22\' outputmatrix], C_T_sum, k);%output the matrix to an excel sheet
        %xlswrite(['E:\d\Dropbox\Pacbio_analysis\reb1_22\' bulkfile], value_sum, k);
        %%%%%%%%%%%%%%%%%%%%%%%%%%%
%          C_T_all_sum(k).C_T_sum_m = C_T_sum_m;
%          C_T_all_sum(k).C_T_sum_r = C_T_sum_r;
        C_T_all_sum(k).C_T_sum_trim = C_T_sum_trim;
        C_T_all_sum(k).C_T_pos = position(1,:);%write C_T_sum and position to a structure
%          C_T_all_sum(k).value_sum_m = value_sum_m;
%          C_T_all_sum(k).value_sum_r = value_sum_r;
        C_T_all_sum(k).value_sum_trim = value_sum_trim;
        %save_data('E:\d\Dropbox\Pacbio_analysis\bulk\bulk_1.mat',C_T_all_sum);
        %plot(value_sum(3,:),(0-value_sum(2,:)),'LineWidth',2);
        %print(['E:\d\Dropbox\Pacbio_analysis\bwa\fig\8\bwa_8_', num2str(k), '_bulk.png'],'-dpng','-r300');
        %close all force;
        %catch
        %end
    end
    %save_data([folder, '\Pacbio_analysis\202006_comb\matrix\matrix_',name,'.mat'],C_T_all_sum);
    save_data([folder, '\Pacbio_analysis\20190830\matrix\matrix_',name,'_no_trim.mat'],C_T_all_sum);
end
